### ISSUE TITLE
Can't access fine-tuned Data and Checkpoints

### ISSUE THREAD

**Issue by Martin7-1** [wang-weishi/RAP-Gen#3]
Dear Authors:

I appreciated this work. But when I want to download data and checkpoints using command given in README, if failed with permission error. Looks like Google has update their permission strategy. Is there any solution or other place where I can get the fine-tuned data and checkpoint?

Thanks in advance.

**Comment by wang-weishi** [comment]
Hello Martin, thank you for your interests in our work. I think the coporation counterpart side might have changed the policy or certain updates, leading to this permission error. I cannot access the data and checkpoints from Google either. 

You may refer to our paper (https://arxiv.org/pdf/2309.06057), we have provided our figshare artifact in **section eight DATA AVAILABILITY**. It is should be able to download from https://figshare.com/s/a4e95baee01bba14bf4b.

**Comment by Martin7-1** [comment]
Thanks a lot!

**Comment by Martin7-1** [comment]
Hi! @wang-weishi , Thanks for your help.

Currently I found that in `TFix` dataset, the retrieval result is different from the source code. For example:

```
fix no-invalid-this Unexpected 'this'.       this.scanRowId_().then(goog.bind(function(rowId) {
:
      this.db_ = ev.target.result;
      this.scanRowId_().then(goog.bind(function(rowId) {
        lf.Row.setNextId(rowId + 1);
<unk>  rows.forEach(goog.bind(function(row) {<unk>  rows.forEach(function(row) {<unk>      this.buffer_.traverse(goog.bind(this.defaultOnSuccess_, this),<unk>      this.buffer_.traverse(goog.bind(onSuccess, this),
```

The `rows.forEach(goog.bind(function(row) {` is actually not the original source code in `TFix`. Looks like it's the real buggy line in source code.

The question is: How did you get the real buggy line? It is using pattern matching or other methods? I'd appreciated if you could tell me.

**Comment by half-clouds** [comment]
> Thanks a lot!

hello，老哥，请问您是怎么运行起来的？ 我从作者提供的这个链接里https://figshare.com/s/a4e95baee01bba14bf4b.下载了所有的东西，在pretrained_models文件夹里下载了small和base的模型，但我运行起来的时候还是报错：FileNotFoundError: [Errno 2] No such file or directory: 'saved_models/tfix_rmd_rapgen/codet5_small_all_lr5_bs64_src400_trg256_pat30_e30/checkpoint-last/pytorch_model.bin'，可以麻烦老哥帮忙看一下，非常感谢！谢谢了！

**Comment by Martin7-1** [comment]
@half-clouds 需要自己建一下报错中的文件夹然后把 pretrained_models 中的 pytorch_model.bin 移动一下

**Comment by wang-weishi** [comment]
> > Thanks a lot!
> 
> hello，老哥，请问您是怎么运行起来的？ 我从作者提供的这个链接里[https://figshare.com/s/a4e95baee01bba14bf4b.下载了所有的东西，在pretrained_models文件夹里下载了small和base的模型，但我运行起来的时候还是报错：FileNotFoundError](https://figshare.com/s/a4e95baee01bba14bf4b.%E4%B8%8B%E8%BD%BD%E4%BA%86%E6%89%80%E6%9C%89%E7%9A%84%E4%B8%9C%E8%A5%BF%EF%BC%8C%E5%9C%A8pretrained_models%E6%96%87%E4%BB%B6%E5%A4%B9%E9%87%8C%E4%B8%8B%E8%BD%BD%E4%BA%86small%E5%92%8Cbase%E7%9A%84%E6%A8%A1%E5%9E%8B%EF%BC%8C%E4%BD%86%E6%88%91%E8%BF%90%E8%A1%8C%E8%B5%B7%E6%9D%A5%E7%9A%84%E6%97%B6%E5%80%99%E8%BF%98%E6%98%AF%E6%8A%A5%E9%94%99%EF%BC%9AFileNotFoundError): [Errno 2] No such file or directory: 'saved_models/tfix_rmd_rapgen/codet5_small_all_lr5_bs64_src400_trg256_pat30_e30/checkpoint-last/pytorch_model.bin'，可以麻烦老哥帮忙看一下，非常感谢！谢谢了！

要是这类报错，可能需要改一下文件名结构才能跑起来。 我上传公司的server那个是我在Google cloud上验证过的最新版本，可以从新直接跑，figshare那边我开始时候是做数据还有模型的备份，主要是为了让reviewer可以做inference实验，来reproduce 我们的结果。

**Comment by wang-weishi** [comment]
> > > Thanks a lot!
> > 
> > 
> > hello，老哥，请问您是怎么运行起来的？ 我从作者提供的这个链接里[https://figshare.com/s/a4e95baee01bba14bf4b.下载了所有的东西，在pretrained_models文件夹里下载了small和base的模型，但我运行起来的时候还是报错：FileNotFoundError](https://figshare.com/s/a4e95baee01bba14bf4b.%E4%B8%8B%E8%BD%BD%E4%BA%86%E6%89%80%E6%9C%89%E7%9A%84%E4%B8%9C%E8%A5%BF%EF%BC%8C%E5%9C%A8pretrained_models%E6%96%87%E4%BB%B6%E5%A4%B9%E9%87%8C%E4%B8%8B%E8%BD%BD%E4%BA%86small%E5%92%8Cbase%E7%9A%84%E6%A8%A1%E5%9E%8B%EF%BC%8C%E4%BD%86%E6%88%91%E8%BF%90%E8%A1%8C%E8%B5%B7%E6%9D%A5%E7%9A%84%E6%97%B6%E5%80%99%E8%BF%98%E6%98%AF%E6%8A%A5%E9%94%99%EF%BC%9AFileNotFoundError): [Errno 2] No such file or directory: 'saved_models/tfix_rmd_rapgen/codet5_small_all_lr5_bs64_src400_trg256_pat30_e30/checkpoint-last/pytorch_model.bin'，可以麻烦老哥帮忙看一下，非常感谢！谢谢了！
> 
> 要是这类报错，可能需要改一下文件名结构才能跑起来。 我上传公司的server那个是我在Google cloud上验证过的最新版本，可以从新直接跑，figshare那边我开始时候是做数据还有模型的备份，主要是为了让reviewer可以做inference实验，来reproduce 我们的结果。

所以可能Hierarchy有一些出入

**Comment by wang-weishi** [comment]
> Hi! @wang-weishi , Thanks for your help.
> 
> Currently I found that in `TFix` dataset, the retrieval result is different from the source code. For example:
> 
> ```
> fix no-invalid-this Unexpected 'this'.       this.scanRowId_().then(goog.bind(function(rowId) {
> :
>       this.db_ = ev.target.result;
>       this.scanRowId_().then(goog.bind(function(rowId) {
>         lf.Row.setNextId(rowId + 1);
> <unk>  rows.forEach(goog.bind(function(row) {<unk>  rows.forEach(function(row) {<unk>      this.buffer_.traverse(goog.bind(this.defaultOnSuccess_, this),<unk>      this.buffer_.traverse(goog.bind(onSuccess, this),
> ```
> 
> The `rows.forEach(goog.bind(function(row) {` is actually not the original source code in `TFix`. Looks like it's the real buggy line in source code.
> 
> The question is: How did you get the real buggy line? It is using pattern matching or other methods? I'd appreciated if you could tell me.

Hi sorry for my late reply. I have defended my thesis and started work. Don't pay much attention to my school email. I am attending EMNLP 2024 and have time to check that email. To address your question, the original TFix dataset uses EsLint to get the error message and the error bug (a specific line of bug). The buggy line was provided by the TFix author, and you can easily extract the buggy line of code with some postprocessing.  You can refer to the paper section 4.1.1 to get more details about the TFix data format. Thank you for being so patient.

**Comment by half-clouds** [comment]
hello，作者大大，您好，我在测试修复任务的时候，跑的命令是这个：python run_exp.py --model_tag codet5_small --task selfapr_rapgen_P1 --load_model_dir /home/aaa/cqj/RAP-Gen/pretrained_models/codet5_small/pytorch_model.bin --tag_suffix zeroshot。但出现了报错： newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/home/aaa/cqj/RAP-Gen/data/selfapr/defects4j.csv'，具体的报错行应该在：Traceback (most recent call last):
  File "/home/aaa/cqj/RAP-Gen/run_rapgen.py", line 497, in <module>
    main()
  File "/home/aaa/cqj/RAP-Gen/run_rapgen.py", line 459, in main
    df_test = pd.read_csv(d4j_test_file, delimiter='\t')。分析报错原因：主要是在当前的文件夹下没有defects4j.csv文件，可以麻烦作者大大提供一下吗？非常感谢！  
另外，如果我想再重新训练的话，请问是需要做哪些工作呢？可以直接用models.py文件进行训练吗？ 感谢作者大大百忙之中抽空回复，祝您工作愉快！

**Comment by wang-weishi** [comment]
> hello，作者大大，您好，我在测试修复任务的时候，跑的命令是这个：python run_exp.py --model_tag codet5_small --task selfapr_rapgen_P1 --load_model_dir /home/aaa/cqj/RAP-Gen/pretrained_models/codet5_small/pytorch_model.bin --tag_suffix zeroshot。但出现了报错： newline="", FileNotFoundError: [Errno 2] No such file or directory: '/home/aaa/cqj/RAP-Gen/data/selfapr/defects4j.csv'，具体的报错行应该在：Traceback (most recent call last): File "/home/aaa/cqj/RAP-Gen/run_rapgen.py", line 497, in main() File "/home/aaa/cqj/RAP-Gen/run_rapgen.py", line 459, in main df_test = pd.read_csv(d4j_test_file, delimiter='\t')。分析报错原因：主要是在当前的文件夹下没有defects4j.csv文件，可以麻烦作者大大提供一下吗？非常感谢！ 另外，如果我想再重新训练的话，请问是需要做哪些工作呢？可以直接用models.py文件进行训练吗？ 感谢作者大大百忙之中抽空回复，祝您工作愉快！

I write it in English to help the community interested in reproducing our results. This research work was done during my internship with Salesforce. For the IP concerns, the data and checkpoints were uploaded to the Salesforce cloud data bucket. However, it requires additional permissions to view this bucket's metadata and download. I do not have a backup copy in my local environment, and both my co-author Wang Yue and Steven have left Salesforce, so the only possible approach is to check with the Salesforce AI Research Director (my PhD supervisor) Prof Shafiq to see how to make this data and checkpoints publicly available. I will check with him and get back to you as soon as possible.

**Comment by wang-weishi** [comment]
> hello，作者大大，您好，我在测试修复任务的时候，跑的命令是这个：python run_exp.py --model_tag codet5_small --task selfapr_rapgen_P1 --load_model_dir /home/aaa/cqj/RAP-Gen/pretrained_models/codet5_small/pytorch_model.bin --tag_suffix zeroshot。但出现了报错： newline="", FileNotFoundError: [Errno 2] No such file or directory: '/home/aaa/cqj/RAP-Gen/data/selfapr/defects4j.csv'，具体的报错行应该在：Traceback (most recent call last): File "/home/aaa/cqj/RAP-Gen/run_rapgen.py", line 497, in main() File "/home/aaa/cqj/RAP-Gen/run_rapgen.py", line 459, in main df_test = pd.read_csv(d4j_test_file, delimiter='\t')。分析报错原因：主要是在当前的文件夹下没有defects4j.csv文件，可以麻烦作者大大提供一下吗？非常感谢！ 另外，如果我想再重新训练的话，请问是需要做哪些工作呢？可以直接用models.py文件进行训练吗？ 感谢作者大大百忙之中抽空回复，祝您工作愉快！

你可以参考并修改 https://github.com/wang-weishi/RAP-Gen/blob/main/sh/exp_with_args.sh，里面有怎么跑我的code，现在只有 https://figshare.com/s/a4e95baee01bba14bf4b?file=37274779 uploaded 的data里的tasks (tfix_rmd_rapgen，refine_rapgen) 可以跑，等我跟我Prof确认一下怎样access其他的data还有checkpoint，其他的task就能cover了。 

Example:
python run_exp.py --model_tag codet5_base --task refine_rapgen --sub_task medium

**Comment by wang-weishi** [comment]
Since most of my co-authors have left Salesforce Research Asia, I will check with my only co-author who is still working in Salesforce as Research Director, verifying how to make the data and checkpoints publicly available to the community. 

He should have the authority to over-write the permission, or at least he should be able to download and upload the data and checkpoints. I have contacted him and I will actively update the progress. My apologies for the inconvenience to all of you.

**Comment by innocent11er** [comment]
Hello Author, I would like to reproduce your paper, but I am currently unable to obtain the data from the paper. Could you please tell me how to access the SelfAPR data?
